disabled_rules:
  - force_try
  - duplicate_imports
  - function_body_length
  - opening_brace
  - unneeded_synthesized_initializer

opt_in_rules:
  - file_header
  - empty_count
  - inclusive_language

type_name:
  allowed_symbols: ["_"]

type_body_length:
  warning: 250
  error: 400

file_length:
  warning: 500
  error: 1000

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  Indexing Your Heart
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/
                    \/\/  This file is part of Indexing Your Heart\.
                    \/\/
                    \/\/  Indexing Your Heart is non-violent software: you can use, redistribute, and\/or modify it under the terms of the
                    \/\/  CNPLv7\+ as found in the LICENSE file in the source code root directory or at
                    \/\/  \<https:\/\/git\.pixie\.town\/thufie\/npl-builder\>\.
                    \/\/
                    \/\/  Indexing Your Heart comes with ABSOLUTELY NO WARRANTY, to the extent permitted by applicable law\. See the CNPL for
                    \/\/  details\.

custom_rules:
  no_capstone_name:
    name: "Require Public-facing Name"
    regex: "(Head Over Heels)"
    capture_group: 0
    match_kinds:
      - comment
      - identifier
      - string
    message: "Refer to the project by its public-facing name, Indexing Your Heart."
    severity: warning
  there_is_no_god:
    name: "Deity Name Mismatch"
    regex: "(\\b[Gg]od\\b)"
    capture_group: 0
    match_kinds:
      - comment
    message: "There is no god, only Obel."
    severity: warning
