version: 2.1

jobs:
  download_godot:
    macos:
      xcode: 16.4.0
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run: brew install just aria2
      - run: |
          mkdir -p workspace/godot
          cd workspace/godot
          aria2c 'https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_mono_macos.universal.zip'
          unzip Godot_v4.4.1-stable_mono_macos.universal.zip
          rm Godot_v4.4.1-stable_mono_macos.universal.zip
      - persist_to_workspace:
          root: workspace
          paths:
            - godot
  unit_test:
    macos:
      xcode: 16.4.0
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: echo "export PATH='/tmp/workspace/godot/Godot_mono.app/Contents/MacOS:$PATH'" >> "$BASH_ENV"
      - run: echo "export GODOT_BIN='/tmp/workspace/godot/Godot_mono.app/Contents/MacOS/Godot'" >> "$BASH_ENV"
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: brew install dotnet-sdk dotnet@8
      - run: ./Shounin/addons/gdUnit4/runtest.sh -a ./test || if [ $? -eq 101 ]; then echo "warnings"; elif [ $? -eq 0 ]; then echo "success"; else exit 1; fi
      - store_test_results:
          path: ./reports/report_1/results.xml

workflows:
  merge_request:
    jobs:
      - download_godot

# TODO: Enable unit and integration tests once CircleCI offers M1 machines to customers for free
# (see https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718).
      - unit_test:
          requires:
            - download_godot
