version: 2.1

jobs:
  unit_test:
    macos:
      xcode: 15.0.0
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: brew install just aria2
      - run: |
          aria2c 'https://github.com/godotengine/godot/releases/download/4.1.1-stable/Godot_v4.1.1-stable_macos.universal.zip'
          unzip Godot_v4.1.1-stable_macos.universal.zip
          mv Godot.app /tmp/Godot.app
          echo "export PATH='/tmp/Godot.app/Contents/MacOS:$PATH'" >> "$BASH_ENV"
      - run: |
          just fetch-remote-deps
          just build-swift-godot
      - run: just test-all-deps-ci
      - store_test_results:
          path: /tmp/testresults
  lint:
    macos:
      xcode: 15.0.0
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: brew install just swiftlint
      - run: |
          mkdir -p /tmp/bin
          echo 'null' >> /tmp/bin/godot
          chmod +x /tmp/bin/godot
          echo "export PATH='/tmp/bin:$PATH'" >> "$BASH_ENV"
      - run: just lint

workflows:
  merge_request:
    jobs:
      - lint
      - unit_test
