version: 2.1

jobs:
  build_swift_godot:
    macos:
      xcode: 15.0.0
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: brew install just aria2
      - run: |
          aria2c 'https://github.com/godotengine/godot/releases/download/4.1.1-stable/Godot_v4.1.1-stable_macos.universal.zip'
          unzip Godot_v4.1.1-stable_macos.universal.zip
          mv Godot.app /tmp/Godot.app
          echo "export PATH='/tmp/Godot.app/Contents/MacOS:$PATH'" >> "$BASH_ENV"
      - run: |
          just fetch-remote-deps
          just build-swift-godot
      - run: mkdir -p workspace
      - run: cp -rf SwiftGodot/SwiftGodot.xcframework/ workspace/
      - persist-to-workspace:
          root: workspace
          paths:
            - SwiftGodot.xcframework
  unit_test:
    macos:
      xcode: 15.0.0
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: cp -rf /tmp/workspace/SwiftGodot.xcframework ./SwiftGodot
      - run: brew install just aria2
      - run: |
          aria2c 'https://github.com/godotengine/godot/releases/download/4.1.1-stable/Godot_v4.1.1-stable_macos.universal.zip'
          unzip Godot_v4.1.1-stable_macos.universal.zip
          mv Godot.app /tmp/Godot.app
          echo "export PATH='/tmp/Godot.app/Contents/MacOS:$PATH'" >> "$BASH_ENV"
      - run: just test-all-deps-ci
      - store_test_results:
          path: /tmp/testresults
  lint:
    macos:
      xcode: 15.0.0
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: brew install just swiftlint
      - run: |
          mkdir -p /tmp/bin
          echo 'null' >> /tmp/bin/godot
          chmod +x /tmp/bin/godot
          echo "export PATH='/tmp/bin:$PATH'" >> "$BASH_ENV"
      - run: just lint || true
      - run: |
          mkdir -p /tmp/logs
          cp swiftlint*.log /tmp/logs 
      - store_artifacts:
          path: /tmp/logs
          destination: swiftlint

workflows:
  merge_request:
    jobs:
      - build_swift_godot
      - lint
      - unit_test:
          requires:
            - build_swift_godot
