version: 2.1

jobs:
  build_swift_godot:
    macos:
      xcode: 15.0.0
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: brew install just aria2
      - run: |
          aria2c 'https://github.com/godotengine/godot/releases/download/4.1.1-stable/Godot_v4.1.1-stable_macos.universal.zip'
          unzip Godot_v4.1.1-stable_macos.universal.zip
          mv Godot.app /tmp/Godot.app
          echo "export PATH='/tmp/Godot.app/Contents/MacOS:$PATH'" >> "$BASH_ENV"
      - run: |
          just fetch-remote-deps
          just build-swift-godot
      - run: mkdir -p workspace/sg/
      - run: cp -rf SwiftGodot/SwiftGodot.xcframework/ workspace/sg/
      - persist_to_workspace:
          root: workspace
          paths:
            - sg
  integration_test:
    macos:
      xcode: 15.0.0
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: brew install just aria2
      - run: |
          aria2c 'https://github.com/godotengine/godot/releases/download/4.1.1-stable/Godot_v4.1.1-stable_macos.universal.zip'
          unzip Godot_v4.1.1-stable_macos.universal.zip
          mv Godot.app /tmp/Godot.app
          echo "export PATH='/tmp/Godot.app/Contents/MacOS:$PATH'" >> "$BASH_ENV"
      - run: just fetch-tools
      - run: just unswizzle-assets
      - run: just build-all-deps-ci
      - run: |
          mkdir -p /tmp/buildlogs/
          mv *_build.log /tmp/buildlogs/
      - store_artifacts:
          path: /tmp/buildlogs
          destination: dependency_builds
      - run: just test-game
      - run: |
          mkdir -p /tmp/testresults/godot
          cp integration_results_*.xml /tmp/testresults/godot
      - store_test_results:
          path: /tmp/testresults/godot
  unit_test:
    macos:
      xcode: 15.0.0
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: brew install just aria2
      - run: |
          aria2c 'https://github.com/godotengine/godot/releases/download/4.1.1-stable/Godot_v4.1.1-stable_macos.universal.zip'
          unzip Godot_v4.1.1-stable_macos.universal.zip
          mv Godot.app /tmp/Godot.app
          echo "export PATH='/tmp/Godot.app/Contents/MacOS:$PATH'" >> "$BASH_ENV"
      - run: just test-all-deps-ci
      - store_test_results:
          path: /tmp/testresults
  lint:
    macos:
      xcode: 15.0.0
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: brew install just swiftlint
      - run: |
          mkdir -p /tmp/bin
          echo 'null' >> /tmp/bin/godot
          chmod +x /tmp/bin/godot
          echo "export PATH='/tmp/bin:$PATH'" >> "$BASH_ENV"
      - run: just lint || true
      - run: |
          mkdir -p /tmp/logs
          cp swiftlint*.log /tmp/logs 
      - store_artifacts:
          path: /tmp/logs
          destination: swiftlint

workflows:
  merge_request:
    jobs:
      - lint
      - unit_test
      - integration_test
