version: 2.1

jobs:
  download_godot:
    macos:
      xcode: 15.0.0
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run: brew install just aria2
      - run: |
          mkdir -p workspace/godot
          cd workspace/godot
          aria2c 'https://github.com/godotengine/godot/releases/download/4.1.1-stable/Godot_v4.1.1-stable_macos.universal.zip'
          unzip Godot_v4.1.1-stable_macos.universal.zip
          rm Godot_v4.1.1-stable_macos.universal.zip
      - persist_to_workspace:
          root: workspace
          paths:
            - godot
  integration_test:
    macos:
      xcode: 15.0.0
      resource_class: macos.m1.medium.gen1
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: echo "export PATH='/tmp/workspace/godot/Godot.app/Contents/MacOS:$PATH'" >> "$BASH_ENV"
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: brew install just
      - run: just fetch-tools
      - run: just unswizzle-assets
      - run: just build-all-deps-ci
      - run: |
          mkdir -p /tmp/buildlogs/
          mv *_build.log /tmp/buildlogs/
      - store_artifacts:
          path: /tmp/buildlogs
          destination: dependency_builds
      - run: just test-game
      - run: |
          mkdir -p /tmp/testresults/godot
          cp integration_results_*.xml /tmp/testresults/godot
      - store_test_results:
          path: /tmp/testresults/godot
  unit_test:
    macos:
      xcode: 15.0.0
      resource_class: macos.m1.medium.gen1
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: echo "export PATH='/tmp/workspace/godot/Godot.app/Contents/MacOS:$PATH'" >> "$BASH_ENV"
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: brew install just
      - run: just test-all-deps-ci
      - store_test_results:
          path: /tmp/testresults
  lint:
    macos:
      xcode: 15.0.0
      resource_class: macos.m1.medium.gen1
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: echo "export PATH='/tmp/workspace/godot/Godot.app/Contents/MacOS:$PATH'" >> "$BASH_ENV"
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: brew install just swiftlint
      - run: just lint || true
      - run: |
          mkdir -p /tmp/logs
          cp swiftlint*.log /tmp/logs 
      - store_artifacts:
          path: /tmp/logs
          destination: swiftlint

workflows:
  merge_request:
    jobs:
      - download_godot
      - lint:
          requires:
            - download_godot
      - unit_test:
          requires:
            - download_godot
      - integration_test:
          requires:
            - download_godot
            - unit_test
