name: Run Unit Tests

on:
  push:
    branches: [ root, devel, prototype, rewrite ]
  pull_request:
    branches: [ root, devel, prototype ]
  workflow_dispatch:


jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: latest-stable
    - uses: extractions/setup-just@v1
    - run: just test-all-deps

