name: Run Unit Tests

on:
  push:
    branches: [ root, devel, prototype, rewrite ]
  pull_request:
    branches: [ root, devel, prototype ]
  workflow_dispatch:


jobs:
  preflight:
    name: Preflight
    runs-on: macos-13

    steps:
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 14.3.0
    - uses: extractions/setup-just@v1
    - uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/godotengine/godot/releases/download/4.0.3-stable/Godot_v4.0.3-stable_macos.universal.zip'
        name: 'godot'
        version: '4.0.3'
        subPath: 'Godot.app/Contents/MacOS/'
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - run: just build-swift-godot
      env:
        SKIP_CLEAN: true
    - uses: actions/upload-artifact@v2
      with:
        name: swiftgodot-package
        path: SwiftGodot/
    - uses: actions/upload-artifact@v2
      with:
        name: swiftgodot-logs
        path: ~/sg-builds/**-build/*.log

  test_unit:
    name: Unit Tests (Libraries)
    runs-on: macos-13
    needs: preflight

    steps:
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 14.3.0
    - uses: extractions/setup-just@v1
    - uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/godotengine/godot/releases/download/4.0.3-stable/Godot_v4.0.3-stable_macos.universal.zip'
        name: 'godot'
        version: '4.0.3'
        subPath: 'Godot.app/Contents/MacOS/'
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: actions/download-artifact@v2
      with:
        name: swiftgodot-package
        path: SwiftGodot
    - run: just test-all-deps

# TODO: Re-enable once Metal is enabled.
# See: https://github.com/actions/runner-images/discussions/6138

#  test_integration:
#    name: Integration Tests (Godot)
#    runs-on: macos-latest
#    needs: preflight
#
#    steps:
#    - uses: maxim-lobanov/setup-xcode@v1.5.1
#      with:
#        xcode-version: latest-stable
#    - uses: extractions/setup-just@v1
#    - uses: supplypike/setup-bin@v3
#      with:
#        uri: 'https://github.com/godotengine/godot/releases/download/4.0.3-stable/Godot_v4.0.3-stable_macos.universal.zip'
#        name: 'godot'
#        version: '4.0.3'
#        subPath: 'Godot.app/Contents/MacOS/'
#    - uses: actions/checkout@v3
#      with:
#        submodules: 'recursive'
#    - run: just build-all-deps
#    - run: just test-game

